version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./:/var/www/html
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./:/var/www/html
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_DATABASE: 'ads'
        command: --init-file /docker-entrypoint-initdb.d/setup.sql
        volumes:
            - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}